# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b2d758be5052f858f0d144c87f5ff595"
name = "free-sample-plus"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"
[[webhooks.subscriptions]]
    uri = "/webhooks/app/scopes_update"
    compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

    [[webhooks.subscriptions]]
    topics = [ "app/uninstalled" ]
    uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products,write_publications"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
